export const FETCH_PATIENT_RECORD_REQUEST = 'FETCH_PATIENT_RECORD_REQUEST';
export const FETCH_PATIENT_RECORD_SUCCESS = 'FETCH_PATIENT_RECORD_SUCCESS';
export const FETCH_PATIENT_RECORD_ERROR = 'FETCH_PATIENT_RECORD_ERROR';
