export const FETCH_PATIENT_RECORD_REQUEST = 'FETCH_PATIENT_RECORD_REQUEST';
export const FETCH_PATIENT_RECORD_SUCCESS = 'FETCH_PATIENT_RECORD_SUCCESS';
export const FETCH_PATIENT_RECORD_ERROR = 'FETCH_PATIENT_RECORD_ERROR';

export const UPDATE_PATIENT_RECORD_REQUEST = 'UPDATE_PATIENT_RECORD_REQUEST';
export const UPDATE_PATIENT_RECORD_SUCCESS = 'UPDATE_PATIENT_RECORD_SUCCESS';
export const UPDATE_PATIENT_RECORD_ERROR = 'UPDATE_PATIENT_RECORD_ERROR';

export const ADD_STAFF_TASK_REQUEST = 'ADD_STAFF_TASK_REQUEST';
export const ADD_STAFF_TASK_SUCCESS = 'ADD_STAFF_TASK_SUCCESS';
export const ADD_STAFF_TASK_ERROR = 'ADD_STAFF_TASK_ERROR';
