export const FETCH_WARDS_REQUEST = 'FETCH WARDS REQUEST';
export const FETCH_WARDS_SUCCESS = 'FETCH WARDS SUCCESS';
export const FETCH_WARDS_FAILED = 'FETCH WARDS FAILED';

export const FETCH_PATIENTS_BY_WARD_REQUEST = 'FETCH PATIENTS BY WARD REQUEST';
export const FETCH_PATIENTS_BY_WARD_SUCCESS = 'FETCH PATIENTS BY WARD SUCCESS';
export const FETCH_PATIENTS_BY_WARD_FAILED = 'FETCH PATIENTS BY WARD FAILED';

export const FETCH_PATIENTS_BY_NAME_REQUEST = 'FETCH PATIENTS BY NAME REQUEST';
export const FETCH_PATIENTS_BY_NAME_SUCCESS = 'FETCH PATIENTS BY NAME SUCCESS';
export const FETCH_PATIENTS_BY_NAME_FAILED = 'FETCH PATIENTS BY NAME FAILED';

// GET WARDS
// GET PATIENTS BY WARD
// GET PATIENT BY NAME